#############################################
#Format:
#FIELD_NAME_FOLLOWED_BY_COLON:
# - SUB OPTION FORMAT: SPACE, DASH, SPACE
#FIELD_NAME:
# - ARGUMENT
#############################################
FACEBOOK_EMAIL: 
 - facebook_address@facebook.com
#- optional second email here [repeat as necessary]
FACEBOOK_PASSWORD: 
 - facebook_email_password1
# - password for second email [repeat as necessary]
OUTLOOK_EMAIL: 
 - outlook_address@outlook.com
#- optional second email here [repeat as necessary]
OUTLOOK_PASSWORD:
 - outlook_email_password1
#- password for second outlook email [repeat as necessary]
NUMBER_OF_DESKTOP_SEARCHES:
 - 30
NUMBER_OF_MOBILE_SEARCHES:
 - 20
